language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email:
    recipients:
      - lethanhvinh95@gmail.com
    on_failure: always
node_js:
  - '9'
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: 5f3515720f71d76f69908a645303a4580e3ab3db
  local-dir: public
  target-branch: master
  on:
    branch: develop